// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAHrvI_8TLlG-YE_uGybYLLwrEmMa1cA0',
    appId: '1:1075931836202:android:d73ad619dd5588e6b0f853',
    messagingSenderId: '1075931836202',
    projectId: 'amit-f21f2',
    databaseURL: 'https://amit-f21f2-default-rtdb.firebaseio.com',
    storageBucket: 'amit-f21f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgT7qAsRy2cnWQGO6Bd7S3aFKSAxLAG20',
    appId: '1:1075931836202:ios:1fe94c7b602b7589b0f853',
    messagingSenderId: '1075931836202',
    projectId: 'amit-f21f2',
    databaseURL: 'https://amit-f21f2-default-rtdb.firebaseio.com',
    storageBucket: 'amit-f21f2.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasics',
  );
}
